---
server:
    install: '1'
    timezone: America/New_York
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: localhost, ip: 192.168.33.99, memory: '512', sharedfolder: ./, enableWindows: '1', useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant
    servername: localhost
php:
    packages:
        - php
        - php-curl
        - php-mysql
        - libapache2-mod-php
xdebug:
    install: '1'
