- name: Install PHP5 Packages
  apt: pkg={{ item }}
       state=latest
  with_items: php.packages

- name: enable php5-mcrypt config
  shell: php5enmod mcrypt;
  notify:
    - restart apache

- name: Ensure timezone is set in php.ini
  ini_file: dest={{ item }}
            section=Date
            option=date.timezone
            value={{ server.timezone }}
            backup=yes
  with_items:
    - /etc/php5/apache2/php.ini
    - /etc/php5/cli/php.ini

- name: display php errors when not in production
  ini_file: dest=/etc/php.ini
            section=PHP
            option=display_errors
            value=On
  notify:
  - restart apache
