---
- hosts: all
  become: true
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - apache
    - php
    - xdebug

  post_tasks:
    - name: open URL
      become: no
      local_action: shell open {{ base_url }}
      ignore_errors: yes
